### ISSUE TITLE
Add Wireguard as a core package

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DNP_CORE#103]
Is there a reason not to add wireguard to the core packages? it was added to the script install this past month, and I know wireguard doesnt work with every setup, but its definitely more stable and easier to use than openVPN for most users.  users keep posting about Wireguard not being installed when using the docs or being asked to change their connection by support staff/volunteers, obviously we only need 1 VPN but it seems Wireguard is gonna eventually be the way to go, especially when we go through the docker network change so we stop using public IP blocks.  

If we don't add WireGuard to the core here we need to at least publish it to the dappstore or add installer links to the not installed "core" packages  pages in the dappmanager, along with the other "core" but not necessary packages, like HTTPS.  Users shouldnt have to lookup the installer ENS (i.e. http://my.dappnode/#/installer/wireguard.dnp.dappnode.eth) for packages most users want. like have wireguard installer link in the VPN tab next to OpenVPN if its not installed, same with HTTPS but in the system Network tab/page where it would be if it was already installed.

**Comment by pablomendezroyo** [comment]
Core packages are those that have defined `type: dncore` at the manifest level. This is a poor restriction and there must be also under the ENS `dnp.dappnode.eth`. Core packages can be divided into:
- Mandatory core packages (non-removable): dappmanager wifi ipfs and bind
- Non-mandatory core packages (removable): wireguard vpn and https

Furthermore the core packages installed when ISO/script may be different deppending on the host machine requirements:
- HTTPS is not installed if ports 443 is in used
- If Wireguard kernel requirements are not match, then vpn package instead of wireguard package will be installed.

The way we update core packages is confusing. The core packages under [`dependencies`](https://github.com/dappnode/DNP_CORE/blob/ff66c8f28d5aef102b211f9350ed0fb63b0bd49b/dappnode_package.json#L23) section of the `DNP_CORE` are the only ones updated in core releases. Only "mandatory" core packages should be updated in a core release.

### To discuss

- All non-mandatory core package should be available in the dappstore: wireguard, https, vpn.
- Should the wifi be a non-mandatory core package? I think it should but allowing users to remove all the "connectivity" packages is dangerous.
- ?

**Comment by alexpeterson91** [comment]
Very good points and thanks for clarifying. Personally I always remove Wi-Fi for security reasons and because half my nodes are cloud based. So I would say it's not mandatory and more and more users are using newer NUCs that need firmware updates or changes to even make the Wi-Fi card work, which necessitates connecting via console already. 
Lets add this to the installer refactor as we need to change the initial setup a bit to make it more intuitive and make sure users don't forget to save the host credentials

**Comment by alexpeterson91** [comment]
And absolutely we neee all non mandatory packages available in the DAppStore. 💯

**Comment by pablomendezroyo** [comment]
Will push this for next release https://github.com/dappnode/DNP_DAPPMANAGER/issues/1146
