### ISSUE TITLE
Migrate docker from pkg to repository

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_CORE#135]
Migrate docker installation method from pkg to repository method. See: https://docs.docker.com/engine/install/debian/

Research risks and recreate the migration

**Comment by dsimog01** [comment]
In order to migrate docker installation from pkg to repository we will probably need to perform the next steps:
1. Remove old docker installation:
`for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done`

2. Install using the docker apt repository:
`https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository`

**Comment by 3alpha** [comment]
We should look into if this can be done without step 1. I think it should be possible.
